# Deobfuscated and Leaked by FlatiCommunity (https://t.me/flaticommunity)
# мы ебались уже 2 недели для фикса ебаных стрингов зкмки, БЛЯТЬ ВМКУ НЕ ПОСТАВИЛИ В ДЕОБФ БЛЯТЬ!!!!!!!!!!!!! VMSECURITY SYKA BLYAT EBATB PIZDA NAXYU. EZ OBF ZKM 14, DES AND STRINGS))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
name: OwlsGuard
version: 1.0
main: ua.owlstudio.owlsguard.Cracker
author: WinLocker